app/models/Book.py
from app import db
from sqlalchemy.orm import relationship

class Book(db.Model):

    __tablename__ = "book"

    id = db.Column("id", db.Integer, primary_key=True)
    isbn = db.Column("isbn", db.String(13), nullable=False, unique=True)
    title = db.Column("title", db.String(45), nullable=False)
    author = db.Column("author", db.String(45), nullable=False)
    publisher = db.Column("publisher", db.String(45), nullable=False)
    year = db.Column("year", db.String(5), nullable=False)
    totalStock = db.Column(db.Integer, nullable=False)
    availableStock = db.Column(db.Integer, nullable=False)
    isAvailable = db.Column(db.Boolean, nullable=False, default=True)

    # reservation relation
    reservations = relationship("Reservation", back_populates="book")

    # genre book relation
    genreBook = relationship("GenreBook", back_populates="book")

    def __init__(self, isbn, title, author, publisher, year, totalStock, availableStock):
        self.isbn = isbn
        self.title = title
        self.author = author
        self.publisher = publisher
        self.year = year
        self.totalStock = totalStock
        self.availableStock = availableStock


        if self.availableStock > 0:
            self.isAvailable = True
        else:
            self.isAvailable = False

    def decreaseAvailableStock(self):
        if self.availableStock > 0:
            self.availableStock -= 1

    def increaseAvailableStock(self):
        if self.availableStock < self.totalStock:
            self.availableStock += 1

    def updateIsAvailable(self):
        if self.availableStock > 0:
            self.isAvailable = True
        else:
            self.isAvailable = False

    def __repr__(self):
        return f"<Book {self.title} by {self.author} (ISBN: {self.isbn}, Publisher: {self.publisher}, Year: {self.year}>"

app/models/book.py
from app import db
from sqlalchemy.orm import relationship

class Book(db.Model):

    __tablename__ = "book"

    id = db.Column("id", db.Integer, primary_key=True)
    isbn = db.Column("isbn", db.String(13), nullable=False, unique=True)
    title = db.Column("title", db.String(45), nullable=False)
    author = db.Column("author", db.String(45), nullable=False)
    publisher = db.Column("publisher", db.String(45), nullable=False)
    year = db.Column("year", db.String(5), nullable=False)
    totalStock = db.Column(db.Integer, nullable=False)
    availableStock = db.Column(db.Integer, nullable=False)
    description = db.Column(db.Text, nullable=True)
    isAvailable = db.Column(db.Boolean, nullable=False, default=True)

    # reservation relation
    reservations = relationship("Reservation", back_populates="book")

    # genre book relation
    genreBook = relationship("GenreBook", back_populates="book")

    def __init__(self, isbn, title, author, publisher, year, totalStock, availableStock, description):
        self.isbn = isbn
        self.title = title
        self.author = author
        self.publisher = publisher
        self.year = year
        self.totalStock = totalStock
        self.availableStock = availableStock
        self.description = description

        if self.availableStock > 0:
            self.isAvailable = True
        else:
            self.isAvailable = False

    def decreaseAvailableStock(self):
        if self.availableStock > 0:
            self.availableStock -= 1

    def increaseAvailableStock(self):
        if self.availableStock < self.totalStock:
            self.availableStock += 1

    def updateIsAvailable(self):
        if self.availableStock > 0:
            self.isAvailable = True
        else:
            self.isAvailable = False

    def __repr__(self):
        return f"<Book {self.title} by {self.author} (ISBN: {self.isbn}, Publisher: {self.publisher}, Year: {self.year}>"

app/controllers/BookController.py
from app import db
from ..models.Book import Book
from sqlalchemy import case

class BookController:

    @staticmethod
    def createBook(isbn, title, author, publisher, year, totalStock, availableStock):
        try:
            book = Book(isbn, title, author, publisher, year, totalStock, availableStock)
            db.session.add(book)
            db.session.commit()
            return book
        except Exception as e:
            db.session.rollback()
            return None

    @staticmethod
    def getBookById(book_id):
        try:
            book = Book.query.get(book_id)
            return book
        except Exception as e:
            return None

    @staticmethod
    def getAllBooks():
        try:
            books = Book.query.all()
            return books
        except Exception as e:
            return None


    @staticmethod
    def getSortedBooksByAvailableStock():
        try:
            books = db.session.query(Book).order_by(
                Book.isAvailable.desc(),
                Book.availableStock.desc(),
                Book.title
            ).all()

            return books
        except Exception as e:
            return None

    @staticmethod
    def updateBook(book_id, isbn=None, title=None, author=None, publisher=None, year=None, totalStock=None,
                   availableStock=None, description=None):
        try:
            book = Book.query.get(book_id)
            if not book:
                return None

            if isbn is not None:
                book.isbn = isbn
            if title is not None:
                book.title = title
            if author is not None:
                book.author = author
            if publisher is not None:
                book.publisher = publisher
            if year is not None:
                book.year = year
            if totalStock is not None:
                book.totalStock = totalStock
            if availableStock is not None:
                book.availableStock = availableStock


            db.session.commit()
            return book
        except Exception as e:
            db.session.rollback()
            return None

    @staticmethod
    def deleteBook(book_id):
        try:
            book = Book.query.get(book_id)
            if book:
                db.session.delete(book)
                db.session.commit()
                return True
            return False
        except Exception as e:
            db.session.rollback()
            return False

    @staticmethod
    def findBookByISBN(isbn):
        try:
            book = Book.query.filter_by(isbn=isbn).first()
            return book
        except Exception as e:
            return None

    @staticmethod
    def findBooksByAuthor(author):
        try:
            books = Book.query.filter_by(author=author).all()
            return books
        except Exception as e:
            return None

    @staticmethod
    def findBooksByTitle(title):
        try:
            books = Book.query.filter_by(title=title).all()
            return books
        except Exception as e:
            return None

app/controllers/book_controller.py
from flask import Blueprint, render_template
from flask_login import login_required

# Utils
from app.utils.decorators import *
from app.utils.url_safer import *
from app.utils.mapper import bookMapper

# Services
from app.services.book_service import book_service
from app.services.reservation_service import reservation_service

book_bp = Blueprint('book', __name__, template_folder="../templates/client/book")

# Retorna todos os livros com o id hasheado
@book_bp.route("/", methods=["POST", "GET"])
@login_required
def acervo():
    books = book_service.getSortedBooksByAvailableStock()
    temp_books = []

    # for book in books:
    #     book.id = encode_id(book.id)

    for book in books:
        temp_books.append(bookMapper(book))

    return render_template("acervo.html", books=temp_books, active_page='acervo')


@book_bp.route("/livro-<token>", methods=["POST", "GET"])
@login_required
def reservation_confirm(token):
    book_id = decode_id(token)
    if book_id is None:
        # Lógica para lidar com token inválido
        flash("Token inválido.", "danger")
        return redirect(url_for("book.acervo"))

    book = book_service.findBookById(book_id)
    if book is None:
        # Lógica para lidar com livro não encontrado
        flash("Livro não encontrado.", "danger")
        return redirect(url_for("book.acervo"))

    user_id = current_user.id
    can_reserve = not reservation_service.has_active_reservations(user_id)
    return render_template("reservation-confirm.html", book=book, can_reserve=can_reserve)


@book_bp.route("/reserve/<int:book_id>", methods=["POST"])
@login_required
def reservar(book_id):
    book = book_service.findBookById(book_id)

    if reservation_service.has_active_reservations(current_user.id):
        flash("Você já possui reservas ativas. Não é possível fazer uma nova reserva.", "danger")
    else:
        reservation = reservation_service.createReservation(current_user, book)
        if reservation:
            flash("Reserva realizada com sucesso!", "success")
        else:
            flash("Não foi possível realizar a reserva. Tente novamente.", "danger")
    return redirect(url_for("book.acervo"))

app/templates/client/book/acervo.html
{% extends "base.html" %}

{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endwith %}

<div class="row search-header">
    <div class="col-md-12">
        <form method="POST" id="search-form">
            <div class="input-group rounded mt-3">
                <input type="text" class="form-control mt-0" placeholder="Digite sua pesquisa..."
                       name="input-search">
                <div class="input-group-append">
                    <button class="btn btn-search" type="submit">
                        <img src="{{ url_for('static', filename='img/Vector.png') }}" alt="Pesquisar"
                             style="width: 20px; height: 20px;">
                        <span class="ml-2">Pesquisar</span>
                    </button>
                </div>
            </div>
            <div class="btn-group btn-group-toggle ml-4 w-100" role="group" aria-label="Botões de Filtro"
                 id="botoesFiltro"
                 data-toggle="buttons">
                <span class="filtro-label pt-4">Filtro:</span>
                <div class="btn-group ml-4 d-flex flex-wrap w-100 mb-3" role="group" aria-label="Botões de Filtro">
                    <label class="btn btn-primary mt-4 mb-3 mr-3 w-100 rounded active">
                        <input type="radio" name="filtro" id="filtroTodos" value="filtroTodos" autocomplete="off"
                               checked> Todos
                    </label>
                    <label class="btn btn-primary mt-4 mb-3 mr-3 w-100 rounded">
                        <input type="radio" name="filtro" id="filtroStatus" value="filtroTitulo" autocomplete="off">
                        Título
                    </label>
                    <label class="btn btn-primary mt-4 mb-3 mr-3 w-100 rounded">
                        <input type="radio" name="filtro" id="filtroISBN" value="filtroISBN" autocomplete="off"> ISBN
                    </label>
                    <label class="btn btn-primary mt-4 mb-3 mr-3 w-100 rounded">
                        <input type="radio" name="filtro" id="filtroTitular" value="filtroAutor" autocomplete="off">
                        Autor
                    </label>
                    <select id="filter-select" name="filtro_genero"
                            class="form-select btn btn-outline-secondary-status ml-auto mt-4 mb-3 mr-4 w-100 rounded"
                            aria-label=".form-select filter-select">
                        <option selected disabled>Gênero</option>
                        {% for genre in genre_list %}
                        <option class="text-left" value="{{ genre.id }}">{{ genre.genre_type }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="acervo-container background container mb-5 pt-4 pb-1">
    {% for book in books %}
    <div class="card mb-2">
        <div class="card-body">
            <div class="row align-items-start justify-content-center">
                <div class="imagem col-md-3">
                    <img src="{{ url_for('static', filename='img/book.jpg') }}">
                </div>
                <div class="book-info col-md-8 h-100">
                    <h1 class="title-acervo mb-3">{{ loop.index }}. {{ book.title }}</h1>
                    <hr>
                    <ul class="list-style mb-2">
                        <li class="mb-3">Autor: {{ book.author }}</li>
                        <li class="mb-3">ISBN: {{ book.isbn }}</li>
                        <li class="mb-3">Editora: {{ book.publisher }}</li>
                        <li class="mb-4">Ano: {{ book.year }}</li>
                        <li class="mb-4"><strong>Gênero</strong>
                        {% for genre_book in genre_book_list %}
                        {% if decode_id(book.id) == genre_book.book.id %}
                        - {{ genre_book.genre.genre_type }}
                        {% endif %}
                        {% endfor %}
                        </li>

                    </ul>
                    <div class="row">
                        <div class="col">
                            {% if book.availableStock == 0 %}
                            <a href="#" class="btn bg-unavailable disabled">Indisponível</a>
                            {% else %}
                            <a href="{{ url_for('book.reservation_confirm', token=book.id) }}"
                               class="btn btn-confirm">Reservar</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr class="divider">
    </div>
    {% endfor %}
</div>
<script src="{{ url_for('static', filename='js/filter-submit.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/acervo.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/reservation.css') }}">
{% endblock %}

app/templates/client/book/reservation-confirm.html
{% extends "base.html" %}

{% block content %}
<div class="animate__animated animate__slideInLeft">
    <div class="header-card container">
        <div class="row">
            <div class="col d-flex justify-content-start align-items-center">
                <a href="{{ url_for('book.acervo') }}" class="btn btn-back botao">Voltar</a>
            </div>
            <div class="col d-flex justify-content-center align-items-center">
                <h1 class="titulo">Confirmar Reserva</h1>
            </div>
            <div class="col d-flex justify-content-end align-items-center">
                <form action="{{ url_for('book.reservar', book_id=book.id) }}" method="post">
                    {% if not can_reserve or book.availableStock == 0 %}
                    <button type="submit" class="btn btn-confirm" disabled>Confirmar</button>
                    {% else %}
                    <button type="submit" class="btn btn-confirm">Confirmar</button>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>

    <div class="acervo-container background container mb-5 pt-4 pb-1">
        <div class="card mb-2">
            <div class="card-body">
                <div class="row align-items-start justify-content-center">
                    <div class="imagem-description col-md-3 pt-5">
                        <img src="{{ url_for('static', filename='img/book.jpg') }}">
                    </div>
                    <div class="book-info col-md-8 h-100">

                        <h1 class="title-acervo mb-3">{{ book.title }}</h1>
                        <hr clas="divider">

                        <ul class="list-style mb-2">
                            <li class="text-description mb-3 mt-4" style="text-align: justify;">
                                <strong>Descrição:</strong> {{ book.description }}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endwith %}
</div>

<link rel="stylesheet" href="{{ url_for('static', filename='css/acervo.css') }}">
{% endblock %}