app/models/Reservation.py
from app import db
from sqlalchemy.orm import relationship
from datetime import date, timedelta

class Reservation(db.Model):

    __tablename__ = "reservation"

    id = db.Column(db.Integer, primary_key=True)
    reservationDate = db.Column(db.Date, nullable=False)
    expirationDate = db.Column(db.Date, nullable=False)
    devolutionDate = db.Column(db.Date)
    status = db.Column(db.String(100), nullable=False)
    renewCount = db.Column(db.Integer, default=0)

    # relacionamento com user
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = relationship("User", back_populates="reservations")

    # relacionamento com book
    book_id = db.Column(db.Integer, db.ForeignKey('book.id'), nullable=False)
    book = relationship("Book", back_populates="reservations")

    def __init__(self, user_id, book_id):
        self.reservationDate = date.today()
        self.expirationDate = date.today() + timedelta(days=7)
        self.status = "Ativa"
        self.user_id = user_id
        self.book_id = book_id

    def __repr__(self):
        if self.devolutionDate:
            return f"Reservation('{self.reservationDate}', '{self.expirationDate}', '{self.devolutionDate}', '{self.status}', '{self.user_id}', '{self.book_id}')"
        else:
            return f"Reservation('{self.reservationDate}', '{self.expirationDate}', None, '{self.status}', '{self.user_id}', '{self.book_id}')"

app/models/reservation.py
from app import db
from sqlalchemy.orm import relationship
from datetime import date, timedelta

class Reservation(db.Model):

    __tablename__ = "reservation"

    id = db.Column("id", db.Integer, primary_key=True)
    reservationDate = db.Column(db.Date, nullable=False)
    expirationDate = db.Column(db.Date, nullable=False)
    devolutionDate = db.Column(db.Date, nullable=True)
    status = db.Column(db.String(100), nullable=False)
    renewCount = db.Column(db.Integer, default=0)

    # relacionamento com user
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = relationship("User", back_populates="reservations")

    # relacionamento com book
    book_id = db.Column(db.Integer, db.ForeignKey('book.id'), nullable=False)
    book = relationship("Book", back_populates="reservations")

    def __init__(self, user_id, book_id):
        self.reservationDate = date.today()
        self.expirationDate = date.today() + timedelta(days=7)
        self.status = "Ativa" # Ativa, Atrasada, Finalizada, Espera, Cancelada
        self.user_id = user_id
        self.book_id = book_id

    def __repr__(self):
        if self.devolutionDate:
            return f"Reservation('{self.reservationDate}', '{self.expirationDate}', '{self.devolutionDate}', '{self.status}', '{self.user_id}', '{self.book_id}')"
        else:
            return f"Reservation('{self.reservationDate}', '{self.expirationDate}', None, '{self.status}', '{self.user_id}', '{self.book_id}')"

app/controllers/ReservationController.py
from app import db
from ..models.Reservation import Reservation
from datetime import date, timedelta
from sqlalchemy import or_

class ReservationController:

    """
    FUNÇÕES DE RENOVAÇÃO E DEVOLUÇÃO
    """
    @staticmethod
    def updateStatus(reservation_id):
        try:
            reservation = Reservation.query.get(reservation_id)

            if reservation.expirationDate < date.today():
                reservation.status = "Atrasada"

            if reservation.expirationDate >= date.today():
                reservation.status = "Ativa"

            if reservation.devolutionDate != None:
                reservation.status = "Finalizada"

            db.session.commit()
            return True
        except Exception as e:
            db.session.rollback()
            return False

    @staticmethod
    def renewReservation(reservation):
        try:
            #reservation = Reservation.query.get(reservation_id)
            if reservation.renewCount >= 4:
                return False

            reservation.expirationDate += timedelta(days=7)
            reservation.renewCount += 1
            db.session.commit()

            return True

        except Exception as e:
            db.session.rollback()
            return False

    @staticmethod
    def finishReservation(self, reservation):
        reservation.devolutionDate = date.today()

        if reservation.expirationDate < date.today():
            reservation.status = "Atrasada"
            return False

        reservation.status = "Finalizada"

        # atualiza o status do livro
        book = reservation.book
        book.increaseAvailableStock()
        book.updateIsAvailable()

        db.session.add(reservation)
        db.session.add(book)
        db.session.commit()

        return True # sem multa

    """
    FUNÇÕES BÁSICAS
    """
    # TODO - adm view: findUserByCpf (return user)
    @staticmethod
    def createReservation(user, book):
        try:
            if book.availableStock > 0:

                # faz a reserva e decrementa o valor
                reservation = Reservation(user.id, book.id)
                book.decreaseAvailableStock()

                # atualiza o status do livro
                book.updateIsAvailable()

                # salva no banco
                db.session.add(reservation)
                db.session.add(book)
                db.session.commit()

                return reservation

        except Exception as e:
            db.session.rollback()
            return None

    @staticmethod
    def deleteReservation(reservation_id):
        try:
            reservation = Reservation.query.get(reservation_id)
            if reservation:
                db.session.delete(reservation)
                db.session.commit()
                return True
            else:
                return False
        except Exception as e:
            db.session.rollback()
            return False

    """
    FUNÇÕES DE CONSULTA
    """
    # busca UMA reserva pelo próprio id
    @staticmethod
    def getReservationById(reservation_id):
        try:
            reservation = Reservation.query.get(reservation_id)
            return reservation
        except Exception as e:
            return None

    # busca todas as reservas
    @staticmethod
    def getAllReservations():
        try:
            reservations = Reservation.query.all()
            return reservations
        except Exception as e:
            return None

    # TODO - adm view: findUserByCpf (return user) -> passar user_id
    @staticmethod
    def getReservationsByUser(user_id):
        try:
            reservations = Reservation.query.filter_by(user_id=user_id).all()
            return reservations
        except Exception as e:
            return None

    # busca global em todos os campos de reservas
    @staticmethod
    def getGlobalSearch(user_id, query, books):
        try:
            book_ids = [book.id for book in books]
            reservations = Reservation.query.filter_by(user_id=user_id).filter(Reservation.book_id.in_(book_ids)).all()

            reservations = Reservation.query.filter(
                Reservation.user_id == user_id,
                or_(
                    Reservation.book.has(isbn=query),
                    Reservation.book.has(title=query),
                )
            ).all()
            return reservations
        except Exception as e:
            return None

    # recebe um ID de livro e busca todas as reservas do usuário que possuam esse livro
    @staticmethod
    def getUserReservationsByBooks(user_id, books):
        try:
            book_ids = [book.id for book in books]
            reservations = Reservation.query.filter_by(user_id=user_id).filter(Reservation.book_id.in_(book_ids)).all()
            return reservations
        except Exception as e:
            print(f"Erro ao buscar reservas por livros: {e}")
            return None

    # reservas pelo ISBN (geral)
    @staticmethod
    def getReservationsByBookISBN(isbn):
        try:
            reservations = Reservation.query.filter(Reservation.book.has(isbn=isbn)).all()
            return reservations
        except Exception as e:
            return None

    # reservas pelo ISBN do usuario
    @staticmethod
    def getUserReservationsByBookISBN(user_id, isbn):
        try:
            reservations = Reservation.query.filter(Reservation.user_id == user_id).filter(
                Reservation.book.has(isbn=isbn)).all()
            return reservations
        except Exception as e:
            return None

    # reservas pelo titulo (geral)
    @staticmethod
    def getReservationsByBookTitle(title):
        try:
            reservations = Reservation.query.filter(Reservation.book.has(title=title)).all()
            return reservations
        except Exception as e:
            return None

    # reservas pelo titulo do usuario
    @staticmethod
    def getUserReservationsByBookTitle(user_id, title):
        try:
            print(f"CONTROLLER> Buscando reservas para o usuário {user_id} com o título: {title}")
            reservations = Reservation.query.filter_by(user_id=user_id).filter(Reservation.book.has(title=title)).all()
            print(f"CONTROLLER> Buscando reservas para o usuário {user_id} com o título: {title}")
            return reservations
        except Exception as e:
            return None

    # busca todsas as reservas de um status
    @staticmethod
    def getReservationsByStatus(status):
        try:
            reservations = Reservation.query.filter_by(status=status).all()
            return reservations
        except Exception as e:
            return None

    # busca todas as reservas de um usuário por status
    @staticmethod
    def getUserReservationsByStatus(user_id, status):
        try:
            reservations = Reservation.query.filter_by(user_id=user_id, status=status).all()
            return reservations
        except Exception as e:
            return None

    """
    FUNÇÕES ADICIONAIS
    """
    @staticmethod
    def has_active_reservations(user_id):
        active_reservations = Reservation.query.filter_by(user_id=user_id, status="Ativa").first()
        return bool(active_reservations)

    @staticmethod
    def can_renew(reservation):
        try:
            return (
                reservation.status == "Ativa"
                and reservation.expirationDate >= date.today()
                and reservation.renewCount < 3
            )
        except Exception as e:
            return False

app/controllers/reservation_controller.py
from flask import Blueprint, render_template,redirect, request, url_for, flash
from flask_login import login_required, current_user
from datetime import date

# Utils
from app.utils.url_safer import *
from app.utils.mapper import *

# Services
from app.services import reservation_service
from app.services import book_service

reservation_bp = Blueprint("reservation", __name__, template_folder="../templates/client/reservation")

@reservation_bp.route("/", methods=["POST", "GET"])
@login_required
def reservation():
    reservations = []
    temp_reservations = []

    if request.method == "POST":
        search = request.form.get("input-search")

        filtro_selecionado = request.form.get("filtro")
        filtro_status = request.form.get("filtro-status")

        if filtro_status in ["Ativa", "Finalizada", "Atrasada"]:
            reservations = reservation_service.getUserReservationsByStatus(user_id=current_user.id, status=filtro_status)

        elif filtro_selecionado == "filtroISBN":
            reservations = reservation_service.getUserReservationsByBookISBN(user_id=current_user.id, isbn=search)
            print(reservations)

        elif filtro_selecionado == "filtroTitulo":
            books = book_service.getBooksBySimilarTitle(search)
            if books:
                reservations = reservation_service.getUserReservationsByBooks(user_id=current_user.id, books=books)

        elif filtro_selecionado == "filtroTodos":
            if search:
                reservations = reservation_service.getGlobalSearch(user_id=current_user.id, query=search)
            else:
                reservations = reservation_service.getReservationsByUser(user_id=current_user.id)

    if request.method == "GET":
        reservations = reservation_service.getReservationsByUser(user_id=current_user.id)

    for reservation in reservations:
        temp_reservations.append(reservationMapper(reservation))

    return render_template("reservation-list.html", active_page='reservation', reservations=temp_reservations)


@reservation_bp.route("/r=<token>", methods=["GET", "POST"])
@login_required
def reservation_detail(token):

    reservation_id = decode_id(token)

    print(reservation_id)

    reservation = reservation_service.getReservationById(reservation_id)

    if reservation is None:
        return redirect(url_for("reservation.reservation"))

    reservation_service.updateStatus(reservation_id)

    if request.method == "POST":
        if request.form.get("action") == "renew":
            if reservation.status == "Ativa" and reservation.expirationDate >= date.today() and reservation.renewCount < 3:
                success = reservation_service.renewReservation(reservation)
                if success:
                    flash("Reserva renovada com sucesso!", "success")
                else:
                    flash("Erro ao renovar a reserva.", "error")
            else:
                flash("Não é possível renovar a reserva. A reserva está atrasada ou finalizada.", "error")
        return render_template("reservation-details.html", reservation=reservation)

    can_renew = reservation_service.can_renew(reservation)

    return render_template("reservation-details.html", reservation=reservation, can_renew=can_renew)

app/templates/client/reservation/reservation-details.html
{% extends "base.html" %}
{% block content %}

<div class="header-card container w-100 rounded">
    <div class="row">
        <div class="col d-flex justify-content-start align-items-center">
            <a href="{{ url_for('reservation.reservation') }}" class="btn btn-back botao">Voltar</a>
        </div>
        <div class="col d-flex justify-content-center align-items-center">
            <h1 class="titulo"> Detalhes da Reserva</h1>
        </div>
        <div class="col d-flex justify-content-end align-items-center">
            {% if reservation.status == "Em Espera" %}
            <form method="POST" class="m-0">
                <button type="submit" name="action" value="cancel" class="btn btn-cancel">
                    Cancelar Reserva
                </button>
            </form>
            {% elif reservation.status != "Cancelada" %}
            <form method="POST" class="m-0">
                <button type="submit" name="action" value="renew" class="btn btn-confirm" {% if not can_renew %}disabled
                        style="background-color: gray;" {% endif %}>
                    Renovar
                </button>
            </form>
            {% endif %}
        </div>
    </div>
    <!-- Card dos Detalhes da Reserva -->
    <div>
        <div class="pt-3">
            <div class="card">
                <div class="card-header">
                    Detalhes da Reserva
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <input type="text" class="form-control mb-3"
                               value="Data da Reserva: {{ reservation.reservationDate }}" readonly/>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control mb-3"
                               value="Data de Expiração: {{ reservation.expirationDate }}" readonly/>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control mb-3"
                               value="Data de Devolução: {% if reservation.devolutionDate %}{{ reservation.devolutionDate }}{% elif reservation.status != 'Cancelada' %}Ainda não devolvido{% endif %}"
                               readonly/>
                    </div>
                    <div class="status-box"
                         style="background-color: {% if reservation.status == 'Ativa' %}green{% elif reservation.status == 'Em Espera' %}orange{% elif reservation.status == 'Atrasada' %}red{% elif reservation.status == 'Finalizada' or reservation.status == 'Cancelada' %}gray{% endif %};">
                        Status: {{ reservation.status }}
                    </div>

                    {% if reservation.status != 'Cancelada' and reservation.status != 'Em espera' %}
                    <div class="renov-box">
                        Renovações: {{ reservation.renewCount }}
                    </div>
                    {% endif %}

                </div>
            </div>
        </div>
        <!-- Card do Livro Reservado -->
        <div class="pt-2">
            <div class="card">
                <div class="card-header">
                    Livro Reservado
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <input type="text" class="form-control mb-2" value="Título: {{ reservation.book.title }}"
                               readonly/>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control mb-2" value="Autor: {{ reservation.book.author }}"
                               readonly/>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control mb-2" value="ISBN: {{ reservation.book.isbn }}"
                               readonly/>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control mb-2" value="Ano: {{ reservation.book.year }}" readonly/>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


<link rel="stylesheet" href="{{ url_for('static', filename='css/reservation.css') }}">
{% endblock %}

app/templates/client/reservation/reservation-list.html
{% extends "base.html" %}
{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="flash-message-container">
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} text-center" role="alert">
        {{ message }}
    </div>
    {% endfor %}
</div>
<script>
    setTimeout(function() {
        document.querySelector('.flash-message-container').style.display = 'none';
    }, 5000);
</script>
{% endif %}
{% endwith %}
<div class="header-card container w-100">
    <div class="row">
        <div class="col">
            <div class="d-flex justify-content-start">
            </div>
        </div>
        <div class="col">
            <div class="d-flex justify-content-center">
                <h1 class="titulo">Reservas</h1>
            </div>
        </div>
        <div class="col">
            <div class="d-flex justify-content-end">
            </div>
        </div>
    </div>
</div>
<div class="row search-header">
    <div class="col-md-12">
        <form method="POST" id="search-form">
            <div class="input-group rounded mt-3">
                <input type="text" class="form-control mt-0" placeholder="Digite sua pesquisa..."
                       name="input-search">
                <div class="input-group-append">
                    <button class="btn btn-search" type="submit">
                        <img src="{{ url_for('static', filename='img/Vector.png') }}" alt="Pesquisar"
                             style="width: 20px; height: 20px;">
                        <span class="ml-2">Pesquisar</span>
                    </button>
                </div>
            </div>
            <div class="btn-group btn-group-toggle ml-4 w-100" role="group" aria-label="Botões de Filtro"
                 id="botoesFiltro"
                 data-toggle="buttons">
                <span class="filtro-label pt-4">Filtro:</span>
                <div class="btn-group ml-4 d-flex flex-wrap w-100" role="group" aria-label="Botões de Filtro">
                    <label class="btn btn-primary mt-4 mb-3 mr-3 w-100 rounded active">
                        <input type="radio" name="filtro" id="filtroTodos" value="filtroTodos" autocomplete="off" checked> Todos
                    </label>
                    <label class="btn btn-primary mt-4 mb-3 mr-3 w-100 rounded">
                        <input type="radio" name="filtro" id="filtroTitulo" value="filtroTitulo" autocomplete="off">
                        Título
                    </label>
                    <label class="btn btn-primary mt-4 mb-3 mr-3 w-100 rounded">
                        <input type="radio" name="filtro" id="filtroISBN" value="filtroISBN" autocomplete="off"> ISBN
                    </label>
                    <select id="filter-select" name="filtro-status"
                            class="form-select btn btn-outline-secondary-status ml-auto mt-4 mb-3 mr-4 w-100 rounded"
                            aria-label=".form-select filter-select">
                        <option selected disabled>Status</option>
                        <option class="text-left" value="Ativa">Ativa</option>
                        <option class="text-left" value="Finalizada">Finalizada</option>
                        <option class="text-left" value="Atrasada">Atrasada</option>
                        <option class="text-left" value="Em Espera">Em Espera</option>
                        <option class="text-left" value="Cancelada">Cancelada</option>
                    </select>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="container card">
    <div class="row table-reserve mb-2">
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Título</th>
                    <th scope="col">ISBN</th>
                    <th scope="col">Reserva</th>
                    <th scope="col">Expiração</th>
                    <th scope="col">Status</th>
                    <th scope="col" class="text-center">Ações</th>
                </tr>
                </thead>
                <tbody>
                {% if reservations %}
                {% for reservation in reservations %}
                <tr>
                    <td class="align-middle">{{ reservation.book.title }}</td>
                    <td class="align-middle">{{ reservation.book.isbn }}</td>
                    <td class="align-middle">{{ reservation.reservationDate }}</td>
                    <td class="align-middle">{{ reservation.expirationDate }}</td>
                    <td class="align-middle">{{ reservation.status }}</td>
                    <td class="d-flex justify-content-center align-items-center">
                        <a href="{{ url_for('reservation.reservation_detail', token=reservation.id) }}"
                           class="btn btn-details">Detalhes{{token}}</a>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="6" class="text-center">Nenhuma reserva encontrada.</td>
                </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='js/filter-submit.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/reservation.css') }}">
{% endblock %}