app/models/Reservation.py
from app import db
from sqlalchemy.orm import relationship
from datetime import date, timedelta

class Reservation(db.Model):

    __tablename__ = "reservation"

    id = db.Column(db.Integer, primary_key=True)
    reservationDate = db.Column(db.Date, nullable=False)
    expirationDate = db.Column(db.Date, nullable=False)
    devolutionDate = db.Column(db.Date)
    status = db.Column(db.String(100), nullable=False)
    renewCount = db.Column(db.Integer, default=0)

    # relacionamento com user
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = relationship("User", back_populates="reservations")

    # relacionamento com book
    book_id = db.Column(db.Integer, db.ForeignKey('book.id'), nullable=False)
    book = relationship("Book", back_populates="reservations")

    def __init__(self, user_id, book_id):
        self.reservationDate = date.today()
        self.expirationDate = date.today() + timedelta(days=7)
        self.status = "Ativa"
        self.user_id = user_id
        self.book_id = book_id

    def __repr__(self):
        if self.devolutionDate:
            return f"Reservation('{self.reservationDate}', '{self.expirationDate}', '{self.devolutionDate}', '{self.status}', '{self.user_id}', '{self.book_id}')"
        else:
            return f"Reservation('{self.reservationDate}', '{self.expirationDate}', None, '{self.status}', '{self.user_id}', '{self.book_id}')"

app/models/reservation.py
from app import db
from sqlalchemy.orm import relationship
from datetime import date, timedelta

class Reservation(db.Model):

    __tablename__ = "reservation"

    id = db.Column("id", db.Integer, primary_key=True)
    reservationDate = db.Column(db.Date, nullable=False)
    expirationDate = db.Column(db.Date, nullable=False)
    devolutionDate = db.Column(db.Date, nullable=True)
    status = db.Column(db.String(100), nullable=False)
    renewCount = db.Column(db.Integer, default=0)

    # relacionamento com user
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = relationship("User", back_populates="reservations")

    # relacionamento com book
    book_id = db.Column(db.Integer, db.ForeignKey('book.id'), nullable=False)
    book = relationship("Book", back_populates="reservations")

    def __init__(self, user_id, book_id):
        self.reservationDate = date.today()
        self.expirationDate = date.today() + timedelta(days=7)
        self.status = "Ativa" # Ativa, Atrasada, Finalizada, Espera, Cancelada
        self.user_id = user_id
        self.book_id = book_id

    def __repr__(self):
        if self.devolutionDate:
            return f"Reservation('{self.reservationDate}', '{self.expirationDate}', '{self.devolutionDate}', '{self.status}', '{self.user_id}', '{self.book_id}')"
        else:
            return f"Reservation('{self.reservationDate}', '{self.expirationDate}', None, '{self.status}', '{self.user_id}', '{self.book_id}')"

app/controllers/ReservationController.py
from app import db
from ..models.Reservation import Reservation
from datetime import date, timedelta
from sqlalchemy import or_

class ReservationController:

    """
    FUNÇÕES DE RENOVAÇÃO E DEVOLUÇÃO
    """
    @staticmethod
    def updateStatus(reservation_id):
        try:
            reservation = Reservation.query.get(reservation_id)

            if reservation.expirationDate < date.today():
                reservation.status = "Atrasada"

            if reservation.expirationDate >= date.today():
                reservation.status = "Ativa"

            if reservation.devolutionDate != None:
                reservation.status = "Finalizada"

            db.session.commit()
            return True
        except Exception as e:
            db.session.rollback()
            return False

    @staticmethod
    def renewReservation(reservation):
        try:
            #reservation = Reservation.query.get(reservation_id)
            if reservation.renewCount >= 4:
                return False

            reservation.expirationDate += timedelta(days=7)
            reservation.renewCount += 1
            db.session.commit()

            return True

        except Exception as e:
            db.session.rollback()
            return False

    @staticmethod
    def finishReservation(self, reservation):
        reservation.devolutionDate = date.today()

        if reservation.expirationDate < date.today():
            reservation.status = "Atrasada"
            return False

        reservation.status = "Finalizada"

        # atualiza o status do livro
        book = reservation.book
        book.increaseAvailableStock()
        book.updateIsAvailable()

        db.session.add(reservation)
        db.session.add(book)
        db.session.commit()

        return True # sem multa

    """
    FUNÇÕES BÁSICAS
    """
    # TODO - adm view: findUserByCpf (return user)
    @staticmethod
    def createReservation(user, book):
        try:
            if book.availableStock > 0:

                # faz a reserva e decrementa o valor
                reservation = Reservation(user.id, book.id)
                book.decreaseAvailableStock()

                # atualiza o status do livro
                book.updateIsAvailable()

                # salva no banco
                db.session.add(reservation)
                db.session.add(book)
                db.session.commit()

                return reservation

        except Exception as e:
            db.session.rollback()
            return None

    @staticmethod
    def deleteReservation(reservation_id):
        try:
            reservation = Reservation.query.get(reservation_id)
            if reservation:
                db.session.delete(reservation)
                db.session.commit()
                return True
            else:
                return False
        except Exception as e:
            db.session.rollback()
            return False

    """
    FUNÇÕES DE CONSULTA
    """
    # busca UMA reserva pelo próprio id
    @staticmethod
    def getReservationById(reservation_id):
        try:
            reservation = Reservation.query.get(reservation_id)
            return reservation
        except Exception as e:
            return None

    # busca todas as reservas
    @staticmethod
    def getAllReservations():
        try:
            reservations = Reservation.query.all()
            return reservations
        except Exception as e:
            return None

    # TODO - adm view: findUserByCpf (return user) -> passar user_id
    @staticmethod
    def getReservationsByUser(user_id):
        try:
            reservations = Reservation.query.filter_by(user_id=user_id).all()
            return reservations
        except Exception as e:
            return None

    # busca global em todos os campos de reservas
    @staticmethod
    def getGlobalSearch(user_id, query, books):
        try:
            book_ids = [book.id for book in books]
            reservations = Reservation.query.filter_by(user_id=user_id).filter(Reservation.book_id.in_(book_ids)).all()

            reservations = Reservation.query.filter(
                Reservation.user_id == user_id,
                or_(
                    Reservation.book.has(isbn=query),
                    Reservation.book.has(title=query),
                )
            ).all()
            return reservations
        except Exception as e:
            return None

    # recebe um ID de livro e busca todas as reservas do usuário que possuam esse livro
    @staticmethod
    def getUserReservationsByBooks(user_id, books):
        try:
            book_ids = [book.id for book in books]
            reservations = Reservation.query.filter_by(user_id=user_id).filter(Reservation.book_id.in_(book_ids)).all()
            return reservations
        except Exception as e:
            print(f"Erro ao buscar reservas por livros: {e}")
            return None

    # reservas pelo ISBN (geral)
    @staticmethod
    def getReservationsByBookISBN(isbn):
        try:
            reservations = Reservation.query.filter(Reservation.book.has(isbn=isbn)).all()
            return reservations
        except Exception as e:
            return None

    # reservas pelo ISBN do usuario
    @staticmethod
    def getUserReservationsByBookISBN(user_id, isbn):
        try:
            reservations = Reservation.query.filter(Reservation.user_id == user_id).filter(
                Reservation.book.has(isbn=isbn)).all()
            return reservations
        except Exception as e:
            return None

    # reservas pelo titulo (geral)
    @staticmethod
    def getReservationsByBookTitle(title):
        try:
            reservations = Reservation.query.filter(Reservation.book.has(title=title)).all()
            return reservations
        except Exception as e:
            return None

    # reservas pelo titulo do usuario
    @staticmethod
    def getUserReservationsByBookTitle(user_id, title):
        try:
            print(f"CONTROLLER> Buscando reservas para o usuário {user_id} com o título: {title}")
            reservations = Reservation.query.filter_by(user_id=user_id).filter(Reservation.book.has(title=title)).all()
            print(f"CONTROLLER> Buscando reservas para o usuário {user_id} com o título: {title}")
            return reservations
        except Exception as e:
            return None

    # busca todsas as reservas de um status
    @staticmethod
    def getReservationsByStatus(status):
        try:
            reservations = Reservation.query.filter_by(status=status).all()
            return reservations
        except Exception as e:
            return None

    # busca todas as reservas de um usuário por status
    @staticmethod
    def getUserReservationsByStatus(user_id, status):
        try:
            reservations = Reservation.query.filter_by(user_id=user_id, status=status).all()
            return reservations
        except Exception as e:
            return None

    """
    FUNÇÕES ADICIONAIS
    """
    @staticmethod
    def has_active_reservations(user_id):
        active_reservations = Reservation.query.filter_by(user_id=user_id, status="Ativa").first()
        return bool(active_reservations)

    @staticmethod
    def can_renew(reservation):
        try:
            return (
                reservation.status == "Ativa"
                and reservation.expirationDate >= date.today()
                and reservation.renewCount < 3
            )
        except Exception as e:
            return False

app/controllers/reservation_controller.py
from flask import Blueprint, render_template,redirect, request, url_for, flash
from flask_login import login_required, current_user
from datetime import date

# Utils
from app.utils.url_safer import *
from app.utils.mapper import *

# Services
from app.services import reservation_service
from app.services import book_service

reservation_bp = Blueprint("reservation", __name__, template_folder="../templates/client/reservation")

@reservation_bp.route("/", methods=["POST", "GET"])
@login_required
def reservation():
    reservations = []
    temp_reservations = []

    if request.method == "POST":
        search = request.form.get("input-search")

        filtro_selecionado = request.form.get("filtro")
        filtro_status = request.form.get("filtro-status")

        if filtro_status in ["Ativa", "Finalizada", "Atrasada"]:
            reservations = reservation_service.getUserReservationsByStatus(user_id=current_user.id, status=filtro_status)

        elif filtro_selecionado == "filtroISBN":
            reservations = reservation_service.getUserReservationsByBookISBN(user_id=current_user.id, isbn=search)
            print(reservations)

        elif filtro_selecionado == "filtroTitulo":
            books = book_service.getBooksBySimilarTitle(search)
            if books:
                reservations = reservation_service.getUserReservationsByBooks(user_id=current_user.id, books=books)

        elif filtro_selecionado == "filtroTodos":
            if search:
                reservations = reservation_service.getGlobalSearch(user_id=current_user.id, query=search)
            else:
                reservations = reservation_service.getReservationsByUser(user_id=current_user.id)

    if request.method == "GET":
        reservations = reservation_service.getReservationsByUser(user_id=current_user.id)

    for reservation in reservations:
        temp_reservations.append(reservationMapper(reservation))

    return render_template("reservation-list.html", active_page='reservation', reservations=temp_reservations)


@reservation_bp.route("/r=<token>", methods=["GET", "POST"])
@login_required
def reservation_detail(token):

    reservation_id = decode_id(token)

    print(reservation_id)

    reservation = reservation_service.getReservationById(reservation_id)

    if reservation is None:
        return redirect(url_for("reservation.reservation"))

    reservation_service.updateStatus(reservation_id)

    if request.method == "POST":
        if request.form.get("action") == "renew":
            if reservation.status == "Ativa" and reservation.expirationDate >= date.today() and reservation.renewCount < 3:
                success = reservation_service.renewReservation(reservation)
                if success:
                    flash("Reserva renovada com sucesso!", "success")
                else:
                    flash("Erro ao renovar a reserva.", "error")
            else:
                flash("Não é possível renovar a reserva. A reserva está atrasada ou finalizada.", "error")
        return render_template("reservation-details.html", reservation=reservation)

    can_renew = reservation_service.can_renew(reservation)

    return render_template("reservation-details.html", reservation=reservation, can_renew=can_renew)

app/controllers/user_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user, logout_user

# Services
from app.services.user_service import user_service

user_bp = Blueprint("user", __name__, template_folder="../templates/client/profile")
@user_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

@user_bp.route('/')
@login_required
def profile():
    return render_template("pageuser.html", active_page='profile')

@user_bp.route("/alterar-senha", methods=["POST", "GET"])
@login_required
def change_password():
    if request.method == 'POST':
        action = request.form.get('action')

        current_password = request.form.get('current_password')
        new_password = request.form.get('new_password')
        confirm_password = request.form.get('confirm_password')

        if not current_user.check_password(current_password):
            flash("Senha atual incorreta.", "error")
            return redirect(url_for("user.update_profile"))

        if new_password != confirm_password:
            flash("A nova senha e a confirmação da senha não coincidem.", "erro")
            return redirect(url_for("user.change_password"))

        success = user_service.changePassword(user_id=current_user.id, password=new_password)

        if success:
            flash("Senha alterada com sucesso!", "success")
        else:
            flash("Erro ao alterar a senha.", "error")

        return redirect(url_for("user.profile"))

    return render_template("page-user-att.html", active_page='profile')

@user_bp.route("/editar", methods=["POST", "GET"])
@login_required
def update_profile():
    if request.method == 'POST':
        action = request.form.get('action')

        if action == 'Atualizar':
            name = request.form.get('input_nome')
            phonenumber = request.form.get('input_telefone')

            success = user_service.updateUser(
                user_id=current_user.id,
                name=name,
                phone=phonenumber
            )

            if success:
                flash("Usuário atualizado com sucesso!", "success")
                return redirect(url_for("user.profile"))
            else:
                flash("Erro ao atualizar o usuário.", "error")
                return redirect(url_for("user.update_profile"))

        elif action == 'Excluir Conta':
            success = user_service.deleteUser(user_id=current_user.id)

            if success:
                logout_user()
                flash("Conta apagada com sucesso.", "success")
                return redirect(url_for("user.login"))
            else:
                flash("Erro ao deletar o usuário.", "error")
                return redirect(url_for("user.profile"))

    return render_template("page-user-att.html", active_page='profile')

app/templates/acervo.html
{% extends "base.html" %}

{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endwith %}

<div class="row search-header">
    <div class="col-md-12">
        <form method="POST" id="search-form">
            <div class="input-group rounded mt-3">
                <input type="text" class="form-control mt-0" placeholder="Digite sua pesquisa..." name="input-search">
                <div class="input-group-append">
                    <button class="btn btn-search" type="submit">
                        <img src=".\static\img\Vector.png" alt="Pesquisar" style="width: 20px; height: 20px;">
                        <span class="ml-2">Pesquisar</span>
                    </button>
                </div>
            </div>
            <div class="btn-group btn-group-toggle ml-4 w-100" role="group" aria-label="Botões de Filtro" id="botoesFiltro"
                 data-toggle="buttons">
                <span class="filtro-label pt-4">Filtro:</span>
                <div class="btn-group ml-4 d-flex flex-wrap w-100 mb-3" role="group" aria-label="Botões de Filtro">
                    <label class="btn btn-primary mt-4 mb-3 mr-3 w-100 rounded">
                        <input type="radio" name="filtro" id="filtroTodos" value="filtroTodos" autocomplete="off"
                               checked> Todos
                    </label>
                    <label class="btn btn-primary mt-4 mb-3 mr-3 w-100 rounded">
                        <input type="radio" name="filtro" id="filtroStatus" value="filtroTitulo" autocomplete="off">
                        Título
                    </label>
                    <label class="btn btn-primary mt-4 mb-3 mr-3 w-100 rounded">
                        <input type="radio" name="filtro" id="filtroISBN" value="filtroISBN" autocomplete="off"> ISBN
                    </label>
                    <label class="btn btn-primary mt-4 mb-3 mr-3 w-100 rounded">
                        <input type="radio" name="filtro" id="filtroTitulo" value="filtroAutor" autocomplete="off">
                        Autor
                    </label>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="acervo-container background container mb-5 pt-4 pb-1">
    {% for book in books %}
    <div class="card mb-2">
        <div class="card-body">
            <div class="row align-items-start justify-content-center">
                <div class="imagem col-md-3">
                    <img src="{{ url_for('static', filename='img/book.jpg') }}">
                </div>
                <div class="book-info col-md-8 h-100">
                    <h1 class="title-acervo mb-3">{{ loop.index }}. {{ book.title }}</h1>
                    <hr>
                    <ul class="list-style mb-2">
                        <li class="mb-3">Autor: {{ book.author }}</li>
                        <li class="mb-3">ISBN: {{ book.isbn }}</li>
                        <li class="mb-3">Editora: {{ book.publisher }}</li>
                        <li class="mb-4">Ano: {{ book.year }}</li>
                    </ul>
                    <div class="row">
                        <div class="col">
                            {% if book.availableStock == 0 %}
                            <a href="#" class="btn bg-unavailable disabled">Indisponível</a>
                            {% endif %}
                            {% if book.availableStock != 0 %}
                            <a href="{{ url_for('reservation_confirm', book_id=book.id) }}" class="btn btn-confirm">Reservar</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <hr class="divider">

    </div>
    {% endfor %}
</div>


<link rel="stylesheet" href="{{ url_for('static', filename='css/acervo.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/reservation.css') }}">
{% endblock %}

app/templates/adm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Bootstrap CSS Setup -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/adm.css') }}">
    <meta charset="UTF-8">
    <title> Bibliomania </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap" rel="stylesheet">
</head>
<body>
<header>
    <!-- Navbar - bootstrap -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/"><img src="{{ url_for('static', filename='img/b.png') }}" width="35" height="35"
                                              class="d-inline-block align-top" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
            <div class="navbar-nav  ">
                <a class="nav-item nav-link m-2{% if active_page == 'profile' %} active{% endif %}"
                   href="{{ url_for('admin_user.profile_adm') }}">Users<span class=" sr-only">(current)</span></a> <a
                    class="nav-item nav-link m-2{% if active_page == 'acervo' %} active{% endif %}"
                    href="{{ url_for('admin_book.acervo') }}">Acervo<span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link m-2{% if active_page == 'reservation' %} active{% endif %}"
                   href="{{ url_for('admin_reservation.reservation_adm') }}">Reservas<span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link d-lg-none m-2" href="#">FAQ</a>
                <a class="nav-item nav-link d-lg-none m-2" href="{{ url_for('admin_user.logout') }}">Sair</a>
            </div>
        </div>
        <div class="dropdown ml-auto d-none d-lg-block">
            <button class="btn btn-header dropdown-toggle" type="button" id="navbarDropdown" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                Olá, {{ current_user.name.split(" ")[0] }}
            </button>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <div class="dropdown-divider"></div>
                <a class="dropdown-item d-flex align-items-center" href="{{ url_for('admin_user.logout') }}"><img
                        src="{{ url_for('static', filename='img/17004.png') }}" width="20" height="20"
                        class="d-inline-block align-center mr-2" alt="">Sair</a>
            </div>
        </div>
    </nav>
</header>
<div class="content container">
    {% block content %}
    {% endblock %}
</div>
</body>
<!-- Boostrap JS Setup -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7H/ubX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Bootstrap CSS Setup -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/page-style.css') }}">
    <meta charset="UTF-8">
    <title> Bibliomania </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap" rel="stylesheet">
</head>
<body>
<header>
    <!-- Navbar - bootstrap -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('book.acervo') }}"><img
                src="{{ url_for('static', filename='img/b.png') }}" width="35" height="35"
                class="d-inline-block align-top" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav mx-auto">
                <a class="nav-item nav-link md-auto m-2{% if active_page == 'acervo' %} active{% endif %}"
                   href="{{ url_for('book.acervo') }}">Acervo<span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link md-auto m-2{% if active_page == 'reservation' %} active{% endif %}"
                   href="{{ url_for('reservation.reservation') }}">Reservas<span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link d-lg-none m-2" href="#">FAQ</a>
                <a class="nav-item nav-link d-lg-none m-2" href="{{ url_for('user.logout') }}">Sair</a>
            </div>
        </div>
        <div class="dropdown ml-auto d-none d-lg-block">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="navbarDropdown" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                Olá, {{ current_user.name.split(" ")[0] }}
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="nav-item nav-link m-2{% if active_page == 'profile' %} active{% endif %}"
                   href="{{ url_for('user.profile') }}">
                    <img
                        src="{{ url_for('static', filename='img/user.png') }}" width="20" height="20"
                        class="d-inline-block align-top mr-2" alt="">Perfil<span
                        class="sr-only"></span></a>
                <a class="dropdown-item d-flex align-items-center" href="#"><img
                        src="{{ url_for('static', filename='img/interrogation.png') }}" width="20" height="20"
                        class="d-inline-block align-top mr-2" alt="">FAQ</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item d-flex align-items-center" href="{{ url_for('user.logout') }}"><img
                        src="{{ url_for('static', filename='img/17004.png') }}" width="20" height="20"
                        class="d-inline-block align-center mr-2" alt="">Sair</a>
            </div>
        </div>
    </nav>
</header>
<div class="content container">
    {% block content %}
    {% endblock %}
</div>
<footer class="custom-footer d-flex align-items-center justify-content-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-12 col-12 mb-4 mb-md-0">Contato: (21) 9 9999-9999</div>
            <div class="col-lg-4 col-md-6 col-12 mb-4 mb-md-0">Copyright © Bibliomania</div>
            <div class="col-lg-4 col-md-6 col-12">Endereço: Rua Amaral Peixoto, Centro</div>
        </div>
    </div>
</footer>
</body>
<!-- Boostrap JS Setup -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7H/ubX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
</html>

app/templates/page-user-att.html
{% extends "base.html" %}
{% block content %}
<div class="header-card container">
    <div class="row">
        <div class="col">
            <div class="d-flex justify-content-start">
                <a href="/profile" class="btn btn-back botao">Voltar</a>
            </div>
        </div>
        <div class="col">
            <div class="d-flex justify-content-center">
                <h1 class="titulo">Atualizar Perfil</h1>
            </div>
        </div>
        <div class="col">
            <div class="d-flex justify-content-end">
                <a class="btn btn-confirm botao2" href="{{ url_for('change_password') }}">Alterar Senha</a>
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-body border border-light">
        <form action="{{ url_for('update_profile') }}" method="post">
            <p>Nome: </p>
            <p><input type="text" class="form-control" name="input_nome" value="{{current_user.name}}"/></p>

            <p>Telefone (com DDD): </p>
            <p><input type="text" class="form-control" name="input_telefone" value="{{current_user.phonenumber}}"
                      pattern="[0-9]{11}" title="Informe um telefone válido (11 dígitos)"/></p>
            <input type="submit" class="btn btn-success" value="Atualizar" name="action"/>
            <input type="submit" class="btn btn-danger" value="Excluir Conta" name="action"/>

        </form>
    </div>
</div>

</div>
{% endblock %}